version: '2'

# do not forget to create a kafka directory

services:
  zookeeper:
    hostname: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    expose:
    - "2181"
    ports:
    - "2181:2181"
    volumes:
    - ./kafka/zk-data:/var/lib/zookeeper/data
    - ./kafka/zk-logs:/var/lib/zookeeper/log  
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD", "nc", "-z", "zookeeper", "2181"]
      interval: 10s
      timeout: 5s
      retries: 3
  
  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONNECT_BOOTSTRAP_SERVERS: localhost:9092
        # KAFKA_CONNECT_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"
      KAFKA_CREATE_TOPICS: "my-topic"
        # KAFKA_CONNECT_REST_PORT: 8082
        # KAFKA_CONNECT_REST_ADVERTISED_HOST_NAME: "localhost"
        # KAFKA_CONNECT_KEY_CONVERTER_SCHEMAS_ENABLE: 0
        # KAFKA_CONNECT_VALUE_CONVERTER_SCHEMAS_ENABLE: 0
        # KAFKA_CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        # KAFKA_CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        # KAFKA_CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        # KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
        # KAFKA_CONNECT_INTERNAL_KEY_CONVERTER_SCHEMAS_ENABLE: 0
        # KAFKA_CONNECT_INTERNAL_VALUE_CONVERTER_SCHEMAS_ENABLE: 0
        # KAFKA_CONNECT_OFFSET_STORAGE_FILE_FILENAME: "/tmp/connect.offsets"
        # KAFKA_CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
    depends_on:
    - zookeeper
    ports:
    - '9092:9092'
    - '8082:8082'
    - '8083:8083'
    - "29092:29092"
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
    - ./kafka/kafka-data:/var/lib/kafka/data
    - ./kafka/kafka-log:/var/log/kafka

  schema-registry:
    image: confluentinc/cp-schema-registry:7.1.0
    hostname: schema-registry
    container_name: schema-registry
    user: root
    depends_on:
      kafka:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
    healthcheck:
      test: nc -z localhost 8081 || exit -1 
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 30s
    volumes:
      - ./kafka/registry:/etc/schema-registry



        #  zookeeper:
        #    image: confluentinc/cp-zookeeper:7.3.2
        #    hostname: zookeeper
        #    container_name: zookeeper
        #    user: root
        #    ports:
        #      - "2181:2181"
        #    environment:
        #      ZOOKEEPER_CLIENT_PORT: 2181
        #      ZOOKEEPER_TICK_TIME: 2000
        #    volumes:
        #      - ./kafka/zk-data:/var/lib/zookeeper/data
        #      - ./kafka/zk-logs:/var/lib/zookeeper/log  
        # 
        #  kafka:
        #    image: confluentinc/cp-server:7.0.1
        #    hostname: kafka
        #    container_name: kafka
        #    user: root
        #    depends_on:
        #      - zookeeper
        #    ports:
        #      - "9092:9092"
        #      - "29092:29092"
        #    environment:
        #      KAFKA_HEAP_OPTS: '-Xms1g -Xmx1g'
        #      KAFKA_BROKER_ID: -1
        #      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        #      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: |
        #        PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        #      KAFKA_ADVERTISED_LISTENERS: |
        #        PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        #      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
        #      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        #      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        #      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
        #      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
        #      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        #      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:8081
        #      KAFKA_NUM_RECOVERY_THREADS_PER_DATA_DIR: 2
        #      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
        #      LOG_DIR: /var/log/kafka
        #      KAFKA_DATA_DIR: /var/lib/kafka
        #      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
        #      CONFLUENT_METRICS_ENABLE: 'false'
        #      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
        #      CONFLUENT_REPORTERS_TELEMETRY_AUTO_ENABLE: "false"
        #    healthcheck:
        #      test: ["CMD", "nc", "-vz", "localhost", "9092"]
        #      interval: 30s
        #      timeout: 10s
        #      retries: 4
        #    volumes:
        #      - ./kafka/kafka-data:/var/lib/kafka/data
        #      - ./kafka/kafka-log:/var/log/kafka


