// Code generated by github.com/actgardner/gogen-avro/v10. DO NOT EDIT.
package schemas

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v10/compiler"
	"github.com/actgardner/gogen-avro/v10/vm"
	"github.com/actgardner/gogen-avro/v10/vm/types"
)

var _ = fmt.Printf

type Job struct {
	Job string `json:"job"`

	Field string `json:"field"`
}

const JobAvroCRC64Fingerprint = "j\x1d\x87\x89\xbc\x8bT&"

func NewJob() Job {
	r := Job{}
	return r
}

func DeserializeJob(r io.Reader) (Job, error) {
	t := NewJob()
	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func DeserializeJobFromSchema(r io.Reader, schema string) (Job, error) {
	t := NewJob()

	deser, err := compiler.CompileSchemaBytes([]byte(schema), []byte(t.Schema()))
	if err != nil {
		return t, err
	}

	err = vm.Eval(r, deser, &t)
	return t, err
}

func writeJob(r Job, w io.Writer) error {
	var err error
	err = vm.WriteString(r.Job, w)
	if err != nil {
		return err
	}
	err = vm.WriteString(r.Field, w)
	if err != nil {
		return err
	}
	return err
}

func (r Job) Serialize(w io.Writer) error {
	return writeJob(r, w)
}

func (r Job) Schema() string {
	return "{\"fields\":[{\"name\":\"job\",\"type\":\"string\"},{\"name\":\"field\",\"type\":\"string\"}],\"name\":\"Job\",\"type\":\"record\"}"
}

func (r Job) SchemaName() string {
	return "Job"
}

func (_ Job) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ Job) SetInt(v int32)       { panic("Unsupported operation") }
func (_ Job) SetLong(v int64)      { panic("Unsupported operation") }
func (_ Job) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ Job) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ Job) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ Job) SetString(v string)   { panic("Unsupported operation") }
func (_ Job) SetUnionElem(v int64) { panic("Unsupported operation") }

func (r *Job) Get(i int) types.Field {
	switch i {
	case 0:
		w := types.String{Target: &r.Job}

		return w

	case 1:
		w := types.String{Target: &r.Field}

		return w

	}
	panic("Unknown field index")
}

func (r *Job) SetDefault(i int) {
	switch i {
	}
	panic("Unknown field index")
}

func (r *Job) NullField(i int) {
	switch i {
	}
	panic("Not a nullable field index")
}

func (_ Job) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ Job) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ Job) HintSize(int)                     { panic("Unsupported operation") }
func (_ Job) Finalize()                        {}

func (_ Job) AvroCRC64Fingerprint() []byte {
	return []byte(JobAvroCRC64Fingerprint)
}

func (r Job) MarshalJSON() ([]byte, error) {
	var err error
	output := make(map[string]json.RawMessage)
	output["job"], err = json.Marshal(r.Job)
	if err != nil {
		return nil, err
	}
	output["field"], err = json.Marshal(r.Field)
	if err != nil {
		return nil, err
	}
	return json.Marshal(output)
}

func (r *Job) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}

	var val json.RawMessage
	val = func() json.RawMessage {
		if v, ok := fields["job"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Job); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for job")
	}
	val = func() json.RawMessage {
		if v, ok := fields["field"]; ok {
			return v
		}
		return nil
	}()

	if val != nil {
		if err := json.Unmarshal([]byte(val), &r.Field); err != nil {
			return err
		}
	} else {
		return fmt.Errorf("no value specified for field")
	}
	return nil
}
